# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-08 16:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20170608_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseorg',
            old_name='course_num',
            new_name='courses',
        ),
    ]
