# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-16 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170601_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='user/default.png', upload_to='user/%Y/%m'),
        ),
    ]
